// Auto-generated types matching Supabase schema
// Extend as needed

export type UserRole =
  | 'super_admin'
  | 'school_admin'
  | 'principal'
  | 'teacher'
  | 'accountant'
  | 'counselor'
  | 'parent'
  | 'student'

export type StudentStatus = 'active' | 'inactive' | 'transferred' | 'passed_out' | 'suspended'

export type InquiryStatus =
  | 'new'
  | 'follow_up'
  | 'interested'
  | 'documents_submitted'
  | 'entrance_exam'
  | 'approved'
  | 'fee_pending'
  | 'admitted'
  | 'rejected'
  | 'lost'

export type ApplicationStatus =
  | 'pending'
  | 'counselor_approved'
  | 'documents_verified'
  | 'fee_paid'
  | 'principal_approved'
  | 'admitted'
  | 'rejected'

export type FeeFrequency = 'monthly' | 'quarterly' | 'half_yearly' | 'annually' | 'one_time'
export type PaymentMode = 'cash' | 'cheque' | 'neft' | 'card' | 'upi' | 'online'
export type InvoiceStatus = 'unpaid' | 'partial' | 'paid' | 'cancelled' | 'waived'

export interface School {
  id: string
  name: string
  address?: string
  city?: string
  state?: string
  pincode?: string
  phone?: string
  email?: string
  logo_url?: string
  affiliation_board?: string
  is_active: boolean
  created_at: string
}

export interface User {
  id: string
  school_id: string
  full_name: string
  email: string
  phone?: string
  role: UserRole
  avatar_url?: string
  is_active: boolean
  created_at: string
}

export interface AcademicYear {
  id: string
  school_id: string
  name: string
  start_date: string
  end_date: string
  is_current: boolean
}

export interface Class {
  id: string
  school_id: string
  name: string
  numeric_level?: number
  stream?: string
}

export interface Section {
  id: string
  school_id: string
  class_id: string
  name: string
  class_teacher_id?: string
  max_strength: number
}

export interface House {
  id: string
  school_id: string
  name: string
  color?: string
  badge_url?: string
}

export interface Student {
  id: string
  school_id: string
  admission_number?: string
  first_name: string
  last_name: string
  date_of_birth?: string
  gender?: string
  blood_group?: string
  aadhaar_number?: string
  permanent_address?: string
  city?: string
  state?: string
  phone?: string
  email?: string
  academic_year_id?: string
  class_id?: string
  section_id?: string
  roll_number?: string
  stream?: string
  house_id?: string
  is_house_captain: boolean
  is_school_captain: boolean
  status: StudentStatus
  photo_url?: string
  user_id?: string
  created_at: string
  updated_at: string
}

export interface Parent {
  id: string
  school_id: string
  student_id: string
  father_name?: string
  father_phone?: string
  father_email?: string
  mother_name?: string
  mother_phone?: string
  mother_email?: string
  guardian_name?: string
  guardian_phone?: string
  user_id?: string
}

export interface AdmissionInquiry {
  id: string
  school_id: string
  inquiry_number?: string
  student_name: string
  date_of_birth?: string
  gender?: string
  parent_name: string
  parent_phone: string
  parent_email?: string
  applying_for_class_id?: string
  academic_year_id?: string
  source_id?: string
  counselor_id?: string
  status: InquiryStatus
  notes?: string
  created_at: string
  updated_at: string
}

export interface FeeInvoice {
  id: string
  school_id: string
  student_id: string
  academic_year_id: string
  invoice_number?: string
  invoice_date: string
  due_date?: string
  line_items: FeeLineItem[]
  subtotal: number
  total_discount: number
  late_fine: number
  total_amount: number
  status: InvoiceStatus
  created_at: string
}

export interface FeeLineItem {
  fee_head_id: string
  name: string
  amount: number
  discount: number
  net_amount: number
}

export interface FeePayment {
  id: string
  school_id: string
  invoice_id: string
  student_id: string
  receipt_number?: string
  payment_date: string
  amount_paid: number
  payment_mode: PaymentMode
  transaction_reference?: string
  collected_by?: string
  is_verified: boolean
}

// Request/Response types
export interface PaginationQuery {
  page?: number
  limit?: number
  search?: string
}

export interface ApiResponse<T> {
  success: boolean
  data?: T
  error?: string
  meta?: {
    total: number
    page: number
    limit: number
  }
}

// Database type stub (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      schools: { Row: School; Insert: Partial<School>; Update: Partial<School> }
      users: { Row: User; Insert: Partial<User>; Update: Partial<User> }
      students: { Row: Student; Insert: Partial<Student>; Update: Partial<Student> }
      admission_inquiries: { Row: AdmissionInquiry; Insert: Partial<AdmissionInquiry>; Update: Partial<AdmissionInquiry> }
      fee_invoices: { Row: FeeInvoice; Insert: Partial<FeeInvoice>; Update: Partial<FeeInvoice> }
      fee_payments: { Row: FeePayment; Insert: Partial<FeePayment>; Update: Partial<FeePayment> }
    }
  }
}
